In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('data/survey_results_public.csv', index_col = 'ResponseId')
df.head(10)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
6,I am a developer by profession,45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc....",15.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,GitHub Copilot,NaN,When I have ethical or security concerns about...,designing the architecture in the new domain,120000.0,7.0
7,I am a developer by profession,25-34 years old,Some college/university study without earning ...,"Independent contractor, freelancer, or self-em...",None of the above,9.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,Sentry,NaN,ChatGPT;Claude Code;Google Gemini,NaN,When I don’t trust AI’s answers;When I need he...,NaN,6240.0,6.0
8,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",Employed,Engaged in paid work (20-29 hours per week);Tr...,22.0,"Yes, I am not new to coding but am learning ne...",Books / Physical media;Technical documentation...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Blogs or p...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to learn best practices;When I wan...,"Innovation, system design",72000.0,6.0
9,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,"Caring for dependents (children, elderly, etc....",9.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,70000.0,8.0
10,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,7.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I’m stuck and can’t explain the problem;W...,NaN,5400.0,4.0

To get the specific column after filtering
- first create a variable contains the selected dataframe
- then put into loc to filter

In [4]:
high_salary = df['ConvertedCompYearly'] >= 10000000
df.loc[high_salary, ['LearnCodeChoose', 'LearnCode', 'Age']]

,LearnCodeChoose,LearnCode,Age
ResponseId,,,
28701,"No, I am not new to coding and did not learn n...",NaN,35-44 years old
34268,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...",55-64 years old
35354,"No, I am not new to coding and did not learn n...",NaN,35-44 years old
43144,"Yes, I am not new to coding but am learning ne...",Other (please specify):,18-24 years old
45972,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,55-64 years old
48429,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...",18-24 years old

Using `isin` as `in` function to filter

In [5]:
countries = ['United States', 'India', 'United Kindom', 'Germany']
filt = df['Country'].isin(countries)
df.loc[filt, 'Country']

ResponseId
14         India
16         India
19       Germany
36       Germany
47         India
          ...
49046      India
49047      India
49075      India
49081      India
49090      India
Name: Country, Length: 5564, dtype: object

`str.contains` will check if each `'LanguageHaveWorkedWith'` contains `str` `'Python'` and return a bool value

`na = False` by default

In [6]:
filt = df['LanguageHaveWorkedWith'].str.contains('Python', na = False)
df.loc[filt, 'LanguageHaveWorkedWith']

ResponseId
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
8        Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9                                        Java;Python;Scala
16       Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
18                          HTML/CSS;JavaScript;Python;SQL
                               ...
49062    C;Go;HTML/CSS;JavaScript;MATLAB;MicroPython;Py...
49089                                           Python;SQL
49090    C;C#;C++;HTML/CSS;Java;JavaScript;PHP;PowerShe...
49106    C++;Dart;GDScript;HTML/CSS;JavaScript;PHP;Powe...
49107    Bash/Shell (all shells);Delphi;PowerShell;Pyth...
Name: LanguageHaveWorkedWith, Length: 18444, dtype: object

Rename the column name by using `{}`

In [7]:
df = df.rename(columns = {'LanguageHaveWorkedWith': 'LanguageUsed'})
df['LanguageUsed']

ResponseId
1                         Bash/Shell (all shells);Dart;SQL
2                                                     Java
3                      Dart;HTML/CSS;JavaScript;TypeScript
4                                          Java;Kotlin;SQL
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49119                                                  NaN
49120                                                  NaN
49121                                                  NaN
49122                                               C#;SQL
49123                                                  NaN
Name: LanguageUsed, Length: 49123, dtype: object

In [8]:
df['Employment']

ResponseId
1                                                 Employed
2                                                 Employed
3        Independent contractor, freelancer, or self-em...
4                                                 Employed
5        Independent contractor, freelancer, or self-em...
                               ...
49119                                             Employed
49120                                             Employed
49121                                             Employed
49122                                             Employed
49123                                             Employed
Name: Employment, Length: 49123, dtype: object

Now, if i want to convert all `'Employed'` to `True`, use the `repr()` to check the exact str in it, because it might be `'Employed '` with an extra space after, and use `type()` to check the type, because it might be non-str elements.

In [9]:
print(type(df['Employment'].iloc[1]))
print(repr(df['Employment'].iloc[1:10]))

<class 'str'>
ResponseId
2                                              Employed
3     Independent contractor, freelancer, or self-em...
4                                              Employed
5     Independent contractor, freelancer, or self-em...
6     Independent contractor, freelancer, or self-em...
7     Independent contractor, freelancer, or self-em...
8                                              Employed
9                                              Employed
10                                             Employed
Name: Employment, dtype: object

Then use `map(lambda x:)` to modify every element in the `Employment` column list

In [10]:
df['Employment'] = df['Employment'].map(lambda x: True if x == 'Employed' else False)
df['Employment']

ResponseId
1         True
2         True
3        False
4         True
5        False
         ...
49119     True
49120     True
49121     True
49122     True
49123     True
Name: Employment, Length: 49123, dtype: bool

In [11]:
df['Country']

ResponseId
1            Ukraine
2        Netherlands
3            Ukraine
4            Ukraine
5            Ukraine
            ...
49119            NaN
49120            NaN
49121            NaN
49122         France
49123          Italy
Name: Country, Length: 49123, dtype: object

Using `sort` function to sort people salary within each country

In [12]:
df = df.rename(columns = {'ConvertedCompYearly': 'Salary'})
df['Salary']

ResponseId
1         61256.0
2        104413.0
3         53061.0
4         36197.0
5         60000.0
           ...
49119         NaN
49120         NaN
49121         NaN
49122         NaN
49123         NaN
Name: Salary, Length: 49123, dtype: float64

In [13]:
test = df.sort_values(by = ['Country', 'Salary'], ascending = [True, True])
test[['Salary', 'Country']].head(10)

             Salary      Country
ResponseId
7925          282.0  Afghanistan
6010          986.0  Afghanistan
38609        1000.0  Afghanistan
7167         5200.0  Afghanistan
45925        7042.0  Afghanistan
7077         8450.0  Afghanistan
40307        9858.0  Afghanistan
40967       65000.0  Afghanistan
6836            NaN  Afghanistan
15708           NaN  Afghanistan

`nlargest(int)` filt the largest one then using `loc[filt.index]` select other columns

In [15]:
filt = df['Salary'].nlargest(10)
df.loc[filt.index, 'Country']

ResponseId
34268        United States of America
28701                         Ukraine
43144                          Poland
35354    Iran, Islamic Republic of...
45972                     Netherlands
48429                         Ukraine
24901                           India
10026        United States of America
37353                         Ukraine
30729                          Brazil
Name: Country, dtype: object

Or you can simply display all, or `nsmallest`

In [18]:
df.nlargest(10, 'Salary')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,Salary,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)",False,None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",True,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",True,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",True,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",True,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
48429,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",False,Engaged in paid work (10-19 hours per week);En...,NaN,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000000.0,NaN
24901,I am a developer by profession,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",True,Engaged in paid work (20-29 hours per week),1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,NaN,9531653.0,4.0
10026,I am a developer by profession,25-34 years old,Primary/elementary school,True,Attending school (full-time),2.0,"No, I am not new to coding and did not learn n...",NaN,"No, I learned something that was not related t...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Everything,9000000.0,9.0
37353,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",False,Volunteering (regularly),15.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Videos (not associated with specific online co...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something;When...,"All the same: right tools for proper tasks, co...",6890299.0,7.0
30729,I am a developer by profession,35-44 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)",True,Attending school (part-time);Engaged in paid w...,17.0,"Yes, I am not new to coding but am learning ne...",Stack Overflow or Stack Exchange;Technical doc...,"Yes, I learned how to use AI-enabled tools req...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"problem synthesis, communication, panoramic vi...",6371285.0,8.0